export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export type REQUEST_SUCCESS = typeof REQUEST_SUCCESS;

export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export type REQUEST_FAILURE = typeof REQUEST_FAILURE;